### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__warp_ctc)

### ISSUE THREAD

**Issue by northeastsquare** [SeanNaren/warp-ctc#100]
Hello, after install according README, I got:
>>> from warpctc_pytorch import CTCLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/warpctc_pytorch-0.1-py3.7-linux-x86_64.egg/warpctc_pytorch/__init__.py", line 6, in <module>
    from ._warp_ctc import *
ImportError: dynamic module does not define module export function (PyInit__warp_ctc)
>>> 

pytorch version 1.0.0, and python3.7

**Comment by northeastsquare** [comment]
Solved. use pytorch's cpp extension method

**Comment by Nirvana93** [comment]
i meet the same problem with you, can you tell me more about how to solve this problem? and more about how to use pytorch's cpp extension method, thx

**Comment by northeastsquare** [comment]
Python has its c++ method, while pytorch have pytorch's own method. 
in pytorch_binding/setup.py, change as following:
`
setup(
    name='warpctc',
    ext_modules=[
        # apparently pybind does not support submodules like warpctc._warpctc
        CppExtension('warpctc._warpctc', ['src/_warpctc.cpp'],
                     include_dirs=['../include'],
                     library_dirs=['build/lib'],
                     libraries=['warpctc'],
                     extra_link_args=[make_relative_rpath('lib')])
    ],
    packages=find_packages(exclude=['tests']),
    package_data={'warpctc': ['lib/libwarpctc' + shared_object_ext()]},

    cmdclass={
        'build': Build,
        'build_deps': BuildDeps,
        'build_ext': BuildExtension,
        'clean': Clean,
    })
`
