### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Dinghow** [SeanNaren/warp-ctc#107]
I run the example code in README
```python
import torch
from warpctc_pytorch import CTCLoss
ctc_loss = CTCLoss()
# expected shape of seqLength x batchSize x alphabet_size
probs = torch.FloatTensor([[[0.1, 0.6, 0.1, 0.1, 0.1], [0.1, 0.1, 0.6, 0.1, 0.1]]]).transpose(0, 1).contiguous()
labels = torch.IntTensor([1, 2])
label_sizes = torch.IntTensor([2])
probs_sizes = torch.IntTensor([2])
probs.requires_grad_(True)  # tells autograd to compute gradients for probs
cost = ctc_loss(probs, labels, probs_sizes, label_sizes)
cost.backward()
```
When I execute to `cost = ctc_loss(probs, labels, probs_sizes, label_sizes)`, python crashed with 'Segmentation fault (core dumped)'

My python version is 3.6, pytorch is 1.0.0

**Comment by ZGAI** [comment]
I get the same problem. @Dinghow Have you solved the problem yet?

**Comment by Dinghow** [comment]
@ZGAI Not yet

**Comment by ZGAI** [comment]
@SeanNaren Hi, Could you give us any help? Thanks!

**Comment by ZGAI** [comment]
@Dinghow I have solved it now. You should upgrade your gcc. I upgrade my gcc from 4.8.5 -> 5.4.0.

**Comment by Dinghow** [comment]
@ZGAI Thanks, I will try that way

**Comment by kobenaxie** [comment]
Hi, do we need reinstall pytorch and warp_ctc after upgrade GCC ?

**Comment by Marcovaldong** [comment]
@ZGAI After upgrading the gcc version, did you reinstall the module again? I tried to upgrade the gcc version, tested the module without reinstall it and still got the error (Segmentation fault (core dumped)). 

When I compiled and reinstall the module with gcc 5.4.0, I got the current error when import CTCLoss, did you got this problem?



In [2]: from warpctc_pytorch import CTCLoss                          
---------------------------------------------------------------------
ImportError                         Traceback (most recent call last)
<ipython-input-2-274de07b64f1> in <module>
----> 1 from warpctc_pytorch import CTCLoss

/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/__init__.py in <module>
      4 from torch.nn import Module
      5 
----> 6 from ._warp_ctc import *
      7 
      8 

ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/_warp_ctc.cpython-36m-x86_64-linux-gnu.so)

**Comment by Marcovaldong** [comment]
> @ZGAI After upgrading the gcc version, did you reinstall the module again? I tried to upgrade the gcc version, tested the module without reinstall it and still got the error (Segmentation fault (core dumped)).
> 
> When I compiled and reinstall the module with gcc 5.4.0, I got the current error when import CTCLoss, did you got this problem?
> 
> ## In [2]: from warpctc_pytorch import CTCLoss
> ImportError Traceback (most recent call last)
> in 
> ----> 1 from warpctc_pytorch import CTCLoss
> 
> /disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/**init**.py in 
> 4 from torch.nn import Module
> 5
> ----> 6 from ._warp_ctc import *
> 7
> 8
> 
> ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/_warp_ctc.cpython-36m-x86_64-linux-gnu.so)

I have solved it now. I got this because that I didn't update the softlink of libstdc++.so.6

**Comment by SWHL** [comment]
I have met the same question, and solve it by referring to this [article](https://blog.csdn.net/zerow__/article/details/88845192).
