### ISSUE TITLE
loss is converging but giving wer 100

### ISSUE THREAD

**Issue by vaibhav0195** [SeanNaren/warp-ctc#111]
Hi thanks for this repo,
I am trying to implement wave2Letter using this ctc repo.
But my loss is way too much,in the beginning it decreases steadily upto a value and then stops.
but the model always gives me the blank prediction. can you help me why ?

any help is appreciated 
Thanks :)

**Comment by farisalasmary** [comment]
I had a similar problem and I discovered later that the set of characters that I used in the softmax were all uppercase characters whereas my dataset's set of characters were ALL lowercase.
