### ISSUE TITLE
AttributeError: module 'mxnet.symbol' has no attribute 'WarpCTC'

### ISSUE THREAD

**Issue by sivaaninraj** [SeanNaren/warp-ctc#130]
File "C:\CNN-LSTM-CTC-text-recognition\symbol\lstm.py", line 79, in lstm_unroll
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
AttributeError: module 'mxnet.symbol' has no attribute `'WarpCTC'```

**Comment by SeanNaren** [comment]
Hmm, I'm unsure how WarpCTC is incorporated into MXNET, but this is definitely an issue for mxnet, not warp-ctc
