### ISSUE TITLE
Warning of nvcc

### ISSUE THREAD

**Issue by vadimkantorov** [SeanNaren/warp-ctc#133]
```
ptxas /tmp/tmpxft_00000176_00000000-5_ctc_entrypoint.compute_70.ptx, line 50435; warning : Instruction 'shfl' without '.sync' is deprecated since PTX ISA version 6.0 and will be discontinued in a future PTX ISA version
```

This is compiled with CUDA 10.0.

**Comment by SeanNaren** [comment]
These warnings are fine for CUDA 10, however it seems like in CUDA 10.1 these deprecations have taken effect and require changes to warp-ctc. At that point trying to migrate over to the PyTorch CTC function might be the best bet.
