### ISSUE TITLE
CUDA 10 support 

### ISSUE THREAD

**Issue by vadimkantorov** [SeanNaren/warp-ctc#134]
CMakeLists.txt [needs to be modified](https://github.com/baidu-research/warp-ctc/pull/118). Also suggested in https://github.com/SeanNaren/warp-ctc/issues/116#issuecomment-475145386 .

Otherwise `test_gpu` does not pass and CTCLoss returns 0.0.

```
   IF (CUDA_VERSION GREATER 7.6)
    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_60,code=sm_60")
    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_61,code=sm_61")
    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_62,code=sm_62")
    set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} -gencode arch=compute_70,code=sm_70") ## new line
ENDIF()
```

**Comment by sdzbft** [comment]
you can use CTC Loss in pytorch 1.0.1 directly without warp_ctc

**Comment by SeanNaren** [comment]
warp-ctc does support this compute architecture already, the change was made [here](https://github.com/SeanNaren/warp-ctc/blob/pytorch_bindings/CMakeLists.txt#L51)
