### ISSUE TITLE
warp-ctc can not work. Always segmentation error.

### ISSUE THREAD

**Issue by weitaoatvison** [SeanNaren/warp-ctc#138]
warp-ctc can not work. Always segmentation error. I have test the code under pytorch 1.1.0 and cuda 9.0 or cuda10.0. So I am wondering if the code is right or not?

**Comment by CharlesWu123** [comment]
Hello, Have you solved this problem? I also encountered the same problem.

**Comment by pskrunner14** [comment]
https://github.com/SeanNaren/warp-ctc/issues/62
