### ISSUE TITLE
How to properly install warp-ctc for cuda 10.1

### ISSUE THREAD

**Issue by s-omranpour** [SeanNaren/warp-ctc#157]
```
git clone https://github.com/SeanNaren/warp-ctc.git
cd warp-ctc
mkdir build; cd build
```
In case you don’t have cmake install it: 
`sudo apt install cmake`
`cmake ..`
Then take a look at [this](https://github.com/SeanNaren/deepspeech.pytorch/issues/397) and do what “tq09mx” said.
You need gcc version <= 7 so install it:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt install gcc-7 g++-7
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7 --slave /usr/bin/gcov gcov /usr/bin/gcov-7
```
then,
```
make
export CUDA_HOME="/usr/local/cuda"
cd ../pytorch_binding
python3 setup.py install
```

**Comment by Nosferath** [comment]
Just followed these instructions, including the tq09mx bit. I already had gcc<=7 so I skipped that part. Everything seems to work so far.

Edit: Everything worked well in the end. I found this trying to build warp-ctc with GPU (CUDA) support. The important bit is to export CUDA_HOME before installing.

**Comment by SeanNaren** [comment]
Thanks for opening up this issue, I'll work on getting this fixed in the main branch

**Comment by SeanNaren** [comment]
Merged PR into warp-ctc, pull and rebuild warp-ctc to take effect!
