### ISSUE TITLE
Error when calling CTCLoss()

### ISSUE THREAD

**Issue by ZmeiGorynych** [SeanNaren/warp-ctc#16]
Pytorch 0.4.0a0+408c84d, just rebuilt your fork of warp_ctc from source today.

Feeding some data through an LTSM on GPU, then trying to feed the result to CTC_Loss() as per the documentation.

I can instantiate CTC_Loss() fine, however when I try to call it (line 92 of https://github.com/ZmeiGorynych/basic_pytorch/blob/master/audio_models.py) I get the error

'initializer for ctype \\'struct THIntTensor *\\' must be a pointer to same type, not cdata \\'struct THCudaIntTensor *\\''

All the inputs to the call are on the GPU (I double-checked in debugger). The same call completes fine when everything is on the CPU.

Any idea what the matter could be? Thanks a lot!

**Comment by ZmeiGorynych** [comment]
Ah, got it from reading the test cases!
Even when the probs are on the GPU, the other 3 inputs must still be on the CPU, else the call fails as above.

That's rather an unexpected behavior - what's the reason for that?

**Comment by courao** [comment]
I met the same problem,
did you solve it?

**Comment by XilunWu** [comment]
Same problem here.

**Comment by sh0416** [comment]
Same here.

**Comment by 1LOVESJohnny** [comment]
Hi, how you guys solved this problem?
