### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Luna-yu** [SeanNaren/warp-ctc#185]
(yu_tf_py) root@localhost:/home/yu/yu_ex/warp-ctc/build# make
-- cuda found TRUE
-- Building shared library with GPU support
-- Configuring done
-- Generating done
-- Build files have been written to: /home/yu/yu_ex/warp-ctc/build
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at warpctc_generated_reduce.cu.o.cmake:219 (message):
  Error generating
  /home/yu/yu_ex/warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o

CMakeFiles/warpctc.dir/build.make:70: recipe for target 'CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o' failed
make[2]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/warpctc.dir/all' failed
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Chudbrochil** [comment]
+1
Also experiencing this.

Edit: I resolved my issue by commenting out the old nvcc flags in CMakeLists.txt. Specifically, lines 35-38

**Comment by liangxin123456** [comment]
Thank you very much, I solved the problem through this method

**Comment by dzubke** [comment]
Thanks, @Chudbrochil. This worked for me as well trying to setup warp_ctc using cuda 11.2.

@Luna-yu: if @Chudbrochil solution worked for you, want to close the issue?

**Comment by Luna-yu** [comment]
(yu_tf_py) root@gao-PowerEdge-T640:~/yu_ex/warp-ctc3333/pytorch_binding# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from torch.utils.cpp_extension import BuildExtension, CppExtension
ModuleNotFoundError: No module named 'torch.utils'
(yu_tf_py) root@gao-PowerEdge-T640:~/yu_ex/warp-ctc3333/pytorch_binding# pip install torch.utils
Requirement already satisfied: torch.utils in /root/ana3/envs/yu_tf_py/lib/python3.6/site-packages (0.1.2)
Requirement already satisfied: torch in /root/ana3/envs/yu_tf_py/lib/python3.6/site-packages (from torch.utils) (1.7.1+cu110)
Requirement already satisfied: numpy in /root/ana3/envs/yu_tf_py/lib/python3.6/site-packages (from torch->torch.utils) (1.19.2)
Requirement already satisfied: dataclasses in /root/ana3/envs/yu_tf_py/lib/python3.6/site-packages (from torch->torch.utils) (0.8)
Requirement already satisfied: typing-extensions in /root/ana3/envs/yu_tf_py/lib/python3.6/site-packages (from torch->torch.utils) (3.7.4.3)
I encountered such a problem when running install. Would you like to ask me if you have encountered any?
cuda11.1  torch 1.7.1

**Comment by dzubke** [comment]
This seems like a separate issue. We can continue discussing it on this thread, but you may want to close the issue as it seems like you have successfully run the `make` command. 

Have you tried uninstalling and re-installing pytorch?

What OS are you running? If you're running linux, you can run this command to double check what Cuda version you have installed:
```/usr/local/cuda/bin/nvcc --version```

**Comment by Luna-yu** [comment]
> This seems like a separate issue. We can continue discussing it on this thread, but you may want to close the issue as it seems like you have successfully run the `make` command.
> 
> Have you tried uninstalling and re-installing pytorch?
> 
> What OS are you running? If you're running linux, you can run this command to double check what Cuda version you have installed:
> `/usr/local/cuda/bin/nvcc --version`

thank you！

**Comment by kouohhashi** [comment]
> +1
> Also experiencing this.
> 
> Edit: I resolved my issue by commenting out the old nvcc flags in CMakeLists.txt. Specifically, lines 35-38

Thank you so much!
I have switched to nn.CTCLoss because I could not install warp-ctc but after switching to nn.CTCLoss my accuracy was decreasing...

**Comment by 1ucayu** [comment]
> > +1
> > Also experiencing this.
> > Edit: I resolved my issue by commenting out the old nvcc flags in CMakeLists.txt. Specifically, lines 35-38
> 
> Thank you so much! I have switched to nn.CTCLoss because I could not install warp-ctc but after switching to nn.CTCLoss my accuracy was decreasing...

Lastest version of Pytorch includes CTC in its module, but there are still many project using the early version. :(
