### ISSUE TITLE
Installed successfully but import fails with "torch.utils.ffi is deprecated. Please use cpp extensions instead"

### ISSUE THREAD

**Issue by NiambhB** [SeanNaren/warp-ctc#192]
As above. The install using setup.py finished with no errors but then when I try to import it fails.

I previously got the same error while trying to install, but switching to the branch pytorch_bindings solved it. 

I am using torch 1.9 and cuda 10.2.

**Comment by NiambhB** [comment]
Never mind, recloned and reinstalled and it works now. Probably from me messing around in branches while trying to get it to work.

**Comment by tony8888lrz** [comment]
maybe ur pytorch version should deupdate
