### ISSUE TITLE
ImportError: No module named _warp_ctc

### ISSUE THREAD

**Issue by Eric-Chen-007** [SeanNaren/warp-ctc#30]
After I finish "python setup.py install", when i test the "test.py" in folder "pytorch_binding/tests", i find this error below:
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    from warpctc_pytorch import CTCLoss
  File "build/bdist.linux-x86_64/egg/warpctc_pytorch/__init__.py", line 8, in <module>
ImportError: No module named _warp_ctc

**Comment by r9y9** [comment]
Sorry for this. Should be fixed by #31.

**Comment by xuewenyuan** [comment]
@r9y9 ,but I still have this error

**Comment by r9y9** [comment]
@xuewenyuan Can you try uninstalling the package and then reinstall it again?

**Comment by Eric-Chen-007** [comment]
thank you @r9y9 . problem solved.

**Comment by xuewenyuan** [comment]
@r9y9, yeah, thank you, I solved it. I did not notice that have't been merged.

**Comment by kalanityL** [comment]
Fixed by copying the file: 

_warp_ctc.cpython-36m-x86_64-linux-gnu.so

to 

warp-ctc/pytorch_binding/warpctc_pytorch/

**Comment by manuvector** [comment]
Where is the file _warp_ctc.cpython-36m-x86_64-linux-gnu.so located?

**Comment by manuvector** [comment]
Aah I found it in /usr/local/lib/python3.5/dist-packages/. Cheers
