### ISSUE TITLE
Please enable travis

### ISSUE THREAD

**Issue by bstriner** [SeanNaren/warp-ctc#36]
Thank you for the library. We made a class of 200 students use this project for homework and had some reproducible installation issues, although overall it worked out quite well. Also reproducible in a completely clean docker build. Not sure if those are fixed yet, but I'd like to put up an automated build for a sanity check so nothing big breaks in the future. 

https://github.com/SeanNaren/warp-ctc/pull/12

@SeanNaren can you enable travis so I can try it out? Free CIT is just a few clicks away...

**Comment by SeanNaren** [comment]
Thats awesome to hear! I've enabled it :)

**Comment by SeanNaren** [comment]
Should say I've enabled it for warp-ctc and deepspeech.pytorch

**Comment by r9y9** [comment]
I'm guessing @bstriner meant it would be nice to run tests on Travis to avoid introducing unexpected bugs. e.g., similar to what I did for [merlin](https://github.com/CSTR-Edinburgh/merlin). https://github.com/CSTR-Edinburgh/merlin/pull/263
