### ISSUE TITLE
error: invalid use of incomplete type ‘THFloatTensor {aka struct THFloatTensor}’

### ISSUE THREAD

**Issue by minushuang** [SeanNaren/warp-ctc#47]
errors as the title when I'm running scripts 'python setup.py install' .

![2018-05-03 10-10-38](https://user-images.githubusercontent.com/5811852/39557475-7ddf5a6e-4eba-11e8-88d7-cabbbbe9a077.png)

**Comment by ghost** [comment]
Resolved here : https://github.com/SeanNaren/deepspeech.pytorch/issues/291 (Thanks you !)
