### ISSUE TITLE
TypeError: initializer for ctype 'struct THIntTensor *' must be a pointer to same type, not cdata 'struct THCudaTensor *

### ISSUE THREAD

**Issue by zhly0** [SeanNaren/warp-ctc#49]
Is anybody encounter this problem?

**Comment by zhengwh** [comment]
```
loss = criterion(preds, text, preds_size, label_len)
```

only preds can be cuda type, the other three  shoud be cpu paramters

----------  -------------------------  -----
preds       torch.Size([65, 8, 5530])  True
text        torch.Size([78])           False
preds_size  torch.Size([8])            False
length      torch.Size([8])            False
----------  -------------------------  -----

maybe this will helps you

**Comment by zhly0** [comment]
Thanks for reply，I will try！
