### ISSUE TITLE
pytorch 0.3

### ISSUE THREAD

**Issue by shuangshuangguo** [SeanNaren/warp-ctc#55]
Hi, thank you for sharing the wonderful job!
I just want to know whether it's compatible to pytorch 0.3?
Looking forward to your reply.

**Comment by SeanNaren** [comment]
This is a super late response but the package is, use the commit from [here](https://github.com/SeanNaren/warp-ctc/commit/34ab2673b8c5b99d8fc52bb04d53cfebbfc24fa3). I'll make a tag for the future!
