### ISSUE TITLE
GPU execution requested, but not compiled with GPU support

### ISSUE THREAD

**Issue by MabinogiX** [SeanNaren/warp-ctc#61]
When I use cmake, it said CUDA8.0 found. I have installed it without any problem.
Then I tried to use it in my program, I got two problems.
One is when I calculate ctc loss, I got `GPU execution requested, but not compiled with GPU support` and the program still ran without problem.
In another program, I can calculate ctc loss in cpu, but I can not calculate it in gpu. 
I have run test in cpu and gpu and all tests are passed.
Is there any idea I can solve those problem?

OS: CentOS 7.0
GPU: Tesla P40

**Comment by MabinogiX** [comment]
It turns out to be relative with environment variable.

**Comment by suptimq** [comment]
Hi, so how do u solve the first problem?
What environment variable should be modified?

**Comment by zhangchurong** [comment]
I met the same problem while not knowing how to solve it

**Comment by suptimq** [comment]
My problem is caused by Nvidia Driver, which is I wrongly deleted all the Nvidia packages but still used CUDA when I was training model.

**Comment by zhangchurong** [comment]
> My problem is caused by Nvidia Driver, which is I wrongly deleted all the Nvidia packages but still used CUDA when I was training model.

thank you. but my problem seems more complicated, my gpu works normally.. other program can use it just fine

**Comment by LuluFighting** [comment]
I meet the same problem but don't know how to solve it? Can you share how you deal with this problem?
