### ISSUE TITLE
  #error -- unsupported GNU version! gcc versions later than 6 are not supported!   ^~~~~ CMake Error at warpctc_generated_reduce.cu.o.cmake:219 (message):   Error generating   /home/rice/warp-ctc/build/CMakeFiles/warpctc.dir/src

### ISSUE THREAD

**Issue by Aurora11111** [SeanNaren/warp-ctc#77]
when I run main_crnn.py I  court this issue:
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at warpctc_generated_reduce.cu.o.cmake:219 (message):
  Error generating
  /home/rice/warp-ctc/build/CMakeFiles/warpctc.dir/src
uninstall all the cuda ,cudnn,gcc .cmake 
reinstall cuda(it contains cudnn,gcc,cmake)

**Comment by Aurora11111** [comment]
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
sh: cicc: command not found
CMake Error at warpctc_generated_reduce.cu.o.cmake:279 (message):
  Error generating file
  /home/rice/warp-ctc/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o


make[2]: *** [CMakeFiles/warpctc.dir/build.make:256: CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/warpctc.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

Now,I work it out! just uninstall all the cuda ,cudnn,gcc .cmake
reinstall cuda(it contains cudnn,gcc,cmake)

**Comment by ritwikmishra** [comment]
Instead of uninstalling/reinstalling gcc, I found [this](https://github.com/SeanNaren/warp-ctc/issues/173#issuecomment-720644127) more useful.

**Comment by aa-amory** [comment]
> Instead of uninstalling/reinstalling gcc, I found [this](https://github.com/SeanNaren/warp-ctc/issues/173#issuecomment-720644127) more useful.

I have tried this solution on colab but still not working!!

!pwd
%cd /content
!git clone -b pytorch_bindings https://github.com/SeanNaren/warp-ctc.git
%cd /content/warp-ctc
!mkdir build 
%cd /content/warp-ctc/build
#!cmake ..
!cmake -D CMAKE_C_COMPILER:string=gcc-5 -D CMAKE_CXX_COMPILER=g++-5 ../
!make

**Comment by ritwikmishra** [comment]
> > Instead of uninstalling/reinstalling gcc, I found [this](https://github.com/SeanNaren/warp-ctc/issues/173#issuecomment-720644127) more useful.
> 
> I have tried this solution on colab but still not working!!
> 
> !pwd
> %cd /content
> !git clone -b pytorch_bindings https://github.com/SeanNaren/warp-ctc.git
> %cd /content/warp-ctc
> !mkdir build
> %cd /content/warp-ctc/build
> #!cmake ..
> !cmake -D CMAKE_C_COMPILER:string=gcc-5 -D CMAKE_CXX_COMPILER=g++-5 ../
> !make

what is the error you are observing on Google and on your local?
