### ISSUE TITLE
problem with installing warpctc_pytorch(cuda 9.2, pytorch 0.4.0)

### ISSUE THREAD

**Issue by hdeping** [SeanNaren/warp-ctc#83]
Errors as below:
/warp-ctc-pytorch_bindings/pytorch_binding/src/binding.cpp: In function ‘int gpu_ctc(THCudaTensor*, THCudaTensor*, THIntTensor*, THIntTensor*, THIntTensor*, int, THFloatTensor*, int)’:
/warp-ctc-pytorch_bindings/pytorch_binding/src/binding.cpp:92:49: error: cannot convert ### **_‘THCudaTensor*’ to ‘const THFloatTensor*’ for argument ‘1’ to ‘int64_t THFloatTensor_size(const THFloatTensor*, int)’_**
     int probs_size = THFloatTensor_size(probs, 2);
                                                 ^
/home/ncl/hdp/03_pythonPackage/01_warpctc/warp-ctc-pytorch_bindings/pytorch_binding/src/binding.cpp:106:66: error: cannot convert ‘cudaError_t {aka cudaError}’ to ‘void*’ in initialization
     void* gpu_workspace = THCudaMalloc(state,NULL, gpu_size_bytes);
                                                                  ^
error: command 'gcc' failed with exit status 1

I try to resolve the first error using the function   THCudaTensor_size , so the corresponding code should be:
     int probs_size = THCudaTensor_size(probs,2);

It really worked , however ,  I have no idea to deal with the second one.
Anybody any ideas?

**Comment by hdeping** [comment]
The problem was resloved now, maybe it's caused by the version confliction?
I use the following code toe slove it :  
void  **gpu_workspace ;
THCudaMalloc(state,gpu_workspace, gpu_size_bytes);


Hope to help somebody.

**Comment by ghostliu** [comment]
我也有这样问题，可否解决了啊

**Comment by hdeping** [comment]
现在解决了吗？
Do you resolve it now?

**Comment by 1LOVESJohnny** [comment]
Hey guys, I've found a solution.
source answer: https://www.jianshu.com/p/e948f44c6b37

`Error info: THC_API cudaError_t THCudaMalloc(THCState *state, void **ptr, size_t size);
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1.

Modification: pytorch_binding/src/binding.cpp:
1 at 92 line
    int probs_size = THCudaTensor_size(state, probs, 2);
2 at l05 lines
    void* gpu_workspace;
    THCudaMalloc(state, &gpu_workspace, gpu_size_bytes);`

Done ^_______________________^
