### ISSUE TITLE
linux os, cmake error

### ISSUE THREAD

**Issue by XufengXufengXufeng** [SeanNaren/warp-ctc#88]
pytorch==0.1.12
cuda == 9.0
os == centos7

Error message:
/wangxufeng/warp-ctc-pytorch_bindings/src/ctc_entrypoint.cu(1): error: this declaration has no storage class or type specifier

/wangxufeng/warp-ctc-pytorch_bindings/src/ctc_entrypoint.cu(1): error: expected a ";"

2 errors detected in the compilation of "/tmp/tmpxft_00005d8d_00000000-13_ctc_entrypoint.compute_70.cpp1.ii".
CMake Error at warpctc_generated_ctc_entrypoint.cu.o.cmake:279 (message):
  Error generating file
  /wangxufeng/warp-ctc-pytorch_bindings/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_ctc_entrypoint.cu.o

make[2]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_ctc_entrypoint.cu.o] 错误 1
make[1]: *** [CMakeFiles/warpctc.dir/all] 错误 2
make: *** [all] 错误 2

Somebody, please help. 感激不尽。

**Comment by kobenaxie** [comment]
same error, you solved it ?

**Comment by XufengXufengXufeng** [comment]
@kobenaxie  unfortunately, no. I had to drop the CTCLoss related projects and try some other projects such as https://github.com/chineseocr/chineseocr
for ocr tasks.

**Comment by Allen15rg** [comment]
> same error, you solved it ?
HIi :
I have met a same error, do you have a solution now?

thanks so much!

**Comment by XufengXufengXufeng** [comment]
Sorry, I wasn't able to solve it. @Allen15rg

**Comment by kobenaxie** [comment]
fixed [#99](urlhttps://github.com/SeanNaren/warp-ctc/issues/99)
