### ISSUE TITLE
Installation for PyTorch 1.0 dev version fails

### ISSUE THREAD

**Issue by abuvaneswari** [SeanNaren/warp-ctc#93]
PyTorch 1.0 dev version (torch.__version__ = '1.0.0a0+786f9ba')
Python 3.6
gcc 4.9

I think PyTorch 1.0 onwards, ffi is deprecated... got the following ERROR message...

Can someone please guide me how to use cpp extensions for this repo?

I prefer continuing to use CTCLoss from this repo as I used this for most of my work in the past (I tried using torch.nn.CTCLoss in PyTorch 1.0 and could not get it to match the results given by your CTCLoss())

=====
[ds2pth1@blipp73 pytorch_binding]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from torch.utils.ffi import create_extension
  File "/home/ds2pth1/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

**Comment by code-R** [comment]
@abuvaneswari if you are using pytorch 1.0 version I would suggest to use pytorch CTC loss function, you can find the details below. You have to change the code to use pytorch ctc instead of warp ctc.

Pleae find the below links for more information.
https://pytorch.org/docs/master/nn.html#torch.nn.CTCLoss
https://github.com/pytorch/pytorch/issues/3420#issuecomment-405923080

**Comment by abuvaneswari** [comment]
@code-R , thanks a lot for the info. 

I tried using torch.nn.CTCLoss in the place of warpctc_pytorch.CTCLoss in DeepSpeech2 code (from @SeanNaren) as follows:

Old invocation (warpctc_pytorch):
            criterion = CTCLoss()
            ...
            out = model(inputs)
            out = out.transpose(0, 1)  # TxNxH
            loss = criterion(out, targets, sizes, target_sizes)

New invocation (torch.nn):
            criterion = CTCLoss()
            ...
            out = model(inputs)
            out = out.transpose(0, 1).log_softmax(2).detach().requires_grad_() 
            loss = criterion(out, targets, sizes, target_sizes)

With this, there does not seem to be any learning happening. 'loss' value is a real number (and not a 'nan' or infinity). But the loss value is not going down as the epoch proceeds. I am sure I am doing something wrong in the invocation. Please correct any issues you may see above.

thanks,
Buvana

**Comment by ying09** [comment]
@abuvaneswari You can copy the previous version to pytorch1.0. It also can work.

**Comment by kvcuong** [comment]
Hi,

I tried to replace warp_ctc by CTCLoss of torch but the loss increates rapidly and reaches nan 

-------------------------- =>                     , gt: replaced
-------------------------- =>                     , gt: his
-------------------------- =>                     , gt: the
-------------------------- =>                     , gt: with
-------------------------- =>                     , gt: music
-------------------------- =>                     , gt: Eichmann
-------------------------- =>                     , gt: newly-weds
-------------------------- =>                     , gt: have
-------------------------- =>                     , gt: '
-------------------------- =>                     , gt: the
Test loss: nan, accuray: 0.000000
[1/25][112/149] Loss: nan

Any help ?

**Comment by SeanNaren** [comment]
#89 merged, into pytorch_bindings, should work for 1.0!

**Comment by andrewwyl** [comment]
@kvcuong i face the same issue? can you tell me how to resolve it?  thanks
