### ISSUE TITLE
torch.utils.ffi is depercated

### ISSUE THREAD

**Issue by weizhenzhao** [SeanNaren/warp-ctc#95]
[root@localhost pytorch_binding]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from torch.utils.ffi import create_extension
  File "/usr/lib64/python2.7/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

Hi Dear

I met a new error when running the python setup.py install cmd

can you give me some advice?

thank you very much

weizhen

**Comment by mattroos** [comment]
Seems to be a problem with PyTorch 1.0.  See #93.  There may not be a good solution currently available. :(
